spring:
  profiles:
    active: local
  datasource:
    hikari:
      username: jos
      password: joins1!
      maximum-pool-size: 10
      jdbc-url: jdbc:log4jdbc:mysql://52.79.243.246:3306/BDG?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  type-aliases-package: com.joss.bundaegi/mapper
  mapper-locations: com.joss.bundaegi/mapper/*.xml

logging:
  file:
    path: /logs
    name: application-debug.log

# local

---
server:
  port: 8081
spring:
  profiles: local

# prod
---
server:
  port: 8080
spring:
  profiles: prod




